language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jaeuk9407/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jaeuk9407/docker-react npm run test